### ISSUE TITLE
use flutter-builder for widget building

### ISSUE THREAD

**Issue by softmarshmallow** [naver/zeplin-flutter-gen#9]
https://github.com/bridgedxyz/flutter-builder

this enables you to write promised, consistent, complex widget tree. with js/ts syntax.

e.g.

``` ts
const text = new Text("this is written in typescript", {textStyle: new TextStyle(color: Colors.black)})
console.log(text.build().finalize())

// >>
// Text("this is written in typescript", textStyle: TextStyle(color: Colors.black))
```

(p.s 한국사람)

**Comment by yutae** [comment]
안녕하세요 ! @softmarshmallow  

좋은 오픈소스 프로젝트네요 👍 제안해주셔서 감사합니다.
간단하게 검토해봤지만 적용하기에 어려움이 있을것 같네요. 😭 

- [여러 옵션](https://github.com/naver/zeplin-flutter-gen/blob/70cdcaa7287e547c8d02ed976936de446d0d6e74/src/options.js#L5-L18) 적용 어려움
    - 예를 들면, `Color` 변수화 (`color: AppColor.blue`)
- dart format 적용 어려움

> dartfmt (dart_style)
> The generated code format is set to dartfmt(dart_style) as much as possible.
> You don't need to reformat genrated code.

**Comment by softmarshmallow** [comment]
넵 답변주셔서 감사합니다.
"여러 옵션" 등과같은 확장성은 개인적으로도 필요해서 구현중입니다. dart_style 은 정상작동하지만 어떤 컨택스트에서 주신말씀인진 모르겠네요

해당이쓔는 클로즈해도 무방하며, 위 내용들 업데이트되면 다시 동일쓰래드에 노티한번 드리겠습니다

**Comment by yutae** [comment]
넵 감사합니다. 기대하겠습니다 ! 😄
